name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        node-version: [15.x]
    runs-on: ubuntu-latest
    steps:
      - name: Dotenv Action
        uses: falti/dotenv-action@v0.2.5
        with:
          path: ./.env.test
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: yarn install, build, gen, and test
        run: |
          yarn 
          yarn gen
          yarn build
  test:
    name: Test
    strategy:
      matrix:
        node-version: [15.x]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: seeing-science
        ports:
          - 5432:5432
    steps:
      - name: Dotenv Action
        uses: falti/dotenv-action@v0.2.5
        with:
          path: ./.env.test
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: yarn install, build, gen, and test
        run: |
          yarn 
          yarn gen
          yarn test
